apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-priv
  name: pod-priv
spec:
  containers:
  - args:
    - sleep
    - "999999"
    image: alpine
    name: pod-priv
    resources: {}
    securityContext:
      privileged: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
