apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-ping
  name: pod-ping
spec:
  containers:
  - args:
    - sleep
    - "999999"
    image: alpine
    name: pod-ping
    resources: {}
    securityContext:
      capabilities:
        add:
          - NET_BROADCAST
          - NET_RAW
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
