apiVersion: v1
kind: Pod
metadata:
  name: con-as-user-guest
spec:
  containers:
  - name: one
    image: alpine:latest
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsUser: 1040
  - name: two
    image: alpine:latest
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsUser: 1030
