apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: scaling
  name: scaling
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: scaling
status:
  loadBalancer: {}

