apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    topic: secrets
spec:
  volumes:
  - name: secret-vol
    secret:
      secretName: mysec2
  containers:
  - name: secret-sssh
    image: quay.io/mask365/scaling:latest
    volumeMounts:
    - name: secret-vol
      mountPath: "/etc/sssh"
