apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello
  namespace: myapp
spec:
  containers:
  - image: quay.io/mask365/scaling:latest
    name: hello
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  nodeSelector:
    disktype: ssd
  restartPolicy: Always
